version: "3.9"

services:
  web:
    build: .          # Build from Dockerfile in current dir
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/book_inventory
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_inventory
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# Define the volume here
volumes:
  db_data:
