version: "3.10"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ${HOST_LOGS_PATH}:/app/logs   # Logs mapped to host folder
    restart: on-failure

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ${HOST_DB_PATH}:/var/lib/mysql   # MySQL data mapped to host folder
